### ISSUE TITLE
Sparse matrix

### ISSUE THREAD

**Issue by M-Amrollahi** [a1da4/sppmi-svd#5]
Hi,
Is not it better to use sparse matrix (like csr_matrix or...) instead of M with np.zero type? Because for large corpuses it needs a huge amount of RAM.

**Comment by a1da4** [comment]
Thank you for your comment. I will introduce `scipy.sparce` soon.

**Comment by a1da4** [comment]
Sorry I made you wait.
I added support for `scipy.sparse`. https://github.com/a1da4/sppmi-svd/pull/6
In addition, I made some changes:

1. print -> logging
   1. logging.INFO tells us about the progress
   2. logging.DEBUG tells us about the progress and more information (vocab size, etc)
2. I/O for pre-trained matrix
    1. pre-trained co-occur/sppmi matrices are output as text files.
    2. when you train models with different settings such as a shift parameter or dimension, you can load pre-trained co-occur/sppmi matrices using `--cooccur_pretrained` and `--sppmi_pretrained` arguments.

These differences will be described in [README.md](https://github.com/a1da4/sppmi-svd#readme) soon.

**Comment by M-Amrollahi** [comment]
Hello dear Aida,
If you can change these lines(or any others the same) you are going to get better performance. We can see it in a large corpus:

`M.append(shifted_positive_pmi)`

to 

```
M = []
apnd = M.append
for i in range(x):
    apnd(i)
```
